name: Lint Source Code
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '17 14 * * 1-5' # Run M-F at 2:17pm UTC (7:17am MST / 8:17am MDT)
  workflow_dispatch:

jobs:
  runLinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          package-manager-cache: false
      - run: npm i
      - run: npm run lint:required
