name: Publish NPM Package

on:
 release:
   types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v6
      - name: Get release build
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download ${{ github.event.release.tag_name }} --pattern "harperfast-harper-pro-*.tgz"
      - name: Get version components
        id: version-components
        uses: matt-usurp/validate-semver@v2
        with:
          version: ${{ github.event.release.tag_name }}
      - name: Set package tag
        id: package-tag
        run: |
          if [[ "${{ steps.version-components.outputs.prerelease }}" == '' ]]; then
            echo "packageTag=latest" >> "$GITHUB_OUTPUT"
          else
            echo "packageTag=next" >> "$GITHUB_OUTPUT"
          fi
      - name: Publish package to NPM registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_KEY }}
        run: npm publish --dry-run --tag=${{ steps.package-tag.outputs.packageTag }} harperfast-harper-pro-*.tgz
