name: Publish NPM Package

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    outputs:
      harper-pro-version: ${{ steps.version-components.outputs.version }}
    steps:
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get release build
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download ${{ github.event.release.tag_name }} --pattern "harperfast-harper-pro-*.tgz"
      - name: Get version components
        id: version-components
        uses: matt-usurp/validate-semver@c5050374644a5ab2e03ddca02ce8d282911620ce # v3.0.0
        with:
          version: ${{ github.event.release.tag_name }}
      - name: Set package tag
        id: package-tag
        # Once we have our first full, non-beta release, turn this back on:
        #        run: |
        #          if [[ "${{ steps.version-components.outputs.prerelease }}" == '' ]]; then
        #            echo "packageTag=latest" >> "$GITHUB_OUTPUT"
        #          else
        #            echo "packageTag=next" >> "$GITHUB_OUTPUT"
        #          fi
        # and get rid of this hard coded latest tagging:
        run: |
          echo "packageTag=latest" >> "$GITHUB_OUTPUT"
      - name: Publish package to NPM registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public --tag=${{ steps.package-tag.outputs.packageTag }} harperfast-harper-pro-*.tgz

  send-slack-message-on-success:
    if: success() && !cancelled()
    needs: [publish-npm-package]
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack published notification
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "#development-ci",
              "text": "Harper Pro v${{ needs.publish-npm-package.outputs.harper-pro-version }} has been published to NPM",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Harper Pro v${{ needs.publish-npm-package.outputs.harper-pro-version }} release"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":white_check_mark: Published to :npm:"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<https://www.npmjs.com/package/@harperfast/harper-pro/v/${{ needs.publish-npm-package.outputs.harper-pro-version }}|@harperfast/harper-pro@${{ needs.publish-npm-package.outputs.harper-pro-version }}>"
                    }
                  ]
                }
              ]
            }

  send-slack-message-on-failure:
    if: failure() && !cancelled()
    needs: [publish-npm-package]
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "#development-ci",
              "text": "Harper Pro v${{ needs.publish-npm-package.outputs.harper-pro-version }} NPM publish failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Harper Pro v${{ needs.publish-npm-package.outputs.harper-pro-version }} release"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":x: Failed to publish to :npm:"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow run ${{ github.run_id }}>"
                    }
                  ]
                }
              ]
            }
