name: Sync Core

on:
  repository_dispatch:
    types: [ sync_core ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'

      - name: Sync core
        run: npm run core:sync

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Sync Core'
          branch: sync-core-submodule
          title: 'chore: Sync Core'
          body: |
            Sync core submodule and update package.json dependencies.
            This PR was automatically created by the Sync Core workflow.
          labels: |
            automated pr
            core sync
